
name: tester

on:
  workflow_call:
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.repository.name }}" 
      - run: echo "${{ github.event.repository_owner }}" 
      - run: echo "${{ github.repository.name }}" 
      - run: echo "${{ github.repository_owner }}" 